
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otlp-instrumentation
  namespace: opentelemetry
spec:
  exporter:
    endpoint: http://opentelemetry-demo-collector.opentelemetry:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  nodejs:
    properties:
      volumeLimitSize: "500Mi"
